### ISSUE TITLE
关于PCB版本问题

### ISSUE THREAD

**Issue by kangyuzhe666** [11tools/msiSDR#1]
我之前打了README.md中图片的版本，想问下是否可以正常工作，需要修改哪些电路吗？之前我还下载了一版带有多个LED指示灯的版本，我们看你的项目库中在两个月前和四个月前都有更新，有哪里的变化，电路是否修改，想问下如果我现在重新打板焊接需要更新哪些内容？

**Comment by 11tools** [comment]
图片中的版本也可以工作的，只要确保给msi001供电的飞线即可，clone 最新的不需要改电路和飞线

**Comment by kangyuzhe666** [comment]
> 图片中的版本也可以工作的，只要确保给msi001供电的飞线即可，克隆最新的不需要改电路和飞线

好的
